[package]
name = "ptuber"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of a simplified VTuber rigging software"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9"
serde = { version = "1", features = ["derive"] }
rgb = { version = "0.8", features = ["serde"] }
thiserror = "1.0"
clap = { version = "4", features = ["derive", "cargo"] }
# sfml = { path="./rust-sfml" }
sfml = {git="https://github.com/donicrosby/rust-sfml.git", branch="fix/build-rs-uses-default-toolchain"}
env_logger = "0.10"
log = "0.4"
#[cfg(target_os="linux")]
x11rb = { version = "0.11", features = ["xinerama", "randr"]}
#[cfg(target_os="windows")]
windows = { version = "0.43.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Gdi"] }
cfg-if = "1"
dyn-clone = "1"