debug = false
avatar_below_arm = false

[gamepad]
enabled = true
gamepad_id = 0
mouse_move_joystick = "Left"


[background]
red = 0
green = 0
blue = 0
alpha = 255

[window]
width = 612
height = 467

[mouse_scale]
x = 1.0
y = 1.0
[anchors.anchor]
x = 195
y = 240

[anchors.arm_offset]
x = 67
y = 0

[mouse_mark]
rotation = 15

[mouse_mark.position]
x = 40
y = 290

[mouse_mark.size]
x = 180
y = 90
